version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Computer Science/2. Django Rest Framework/pollsapi/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r "Computer Science/2. Django Rest Framework/pollsapi/requirements.txt"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Computer Science/2. Django Rest Framework/pollsapi/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd "Computer Science/2. Django Rest Framework/pollsapi"
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports